version: "3.8"
services:
  weblogic-lott:
    build:
      context: .
      args:
        - SERVICE_NAME=${SERVICE_NAME}
        - WAR_NAME=${WAR_NAME}
    image: 10.8.90.189:5000/st.win/weblogic-lott:${TAG}
