version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins:lts
    build: .
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /home/docker_workspace/jenkins_workspace:/home/docker_workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    links:
      - 'TCG_LOTT_DB:TCG_LOTT_DB'
    container_name: jenkins_docker

volumes:
  jenkins_home:
    name: jenkins_home
