version: '3.2'

services:
  jenkins:
    image: jenkins/jenkins:lts
    build: .
    ports:
      - 9080:8080
      - 50000:50000
    volumes:
      - /var/docker_workspace:/var/docker_workspace
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    container_name: jenkins_docker

volumes:
  jenkins_home:
networks:
  default:
    external:
      name: network-lott
